### ISSUE TITLE
Go1.7 broke this library

### ISSUE THREAD

**Issue by pyed** [gdm85/go-rencode#1]
> Lastly, there is a minor change to the decompressor's implementation of io.Reader. In previous versions, the decompressor deferred reporting io.EOF until exactly no more bytes could be read. Now, it reports io.EOF more eagerly when reading the last set of bytes.

the outcome is that [`readByte()`](https://github.com/gdm85/go-rencode/blob/master/decoder.go#L50) will read the last byte but won't return it.

**Comment by gdm85** [comment]
Fixed in c8a29a706c939df5531fad06214de31ed0df9b6d

`.Read()` is reading the byte in the slice and returning EOF, whereas before Go 1.7 it would just return EOF without filling in the buffer.

One must always use the returned amount of bytes from a `.Read()` call, so I closed the upstream Go issue too https://github.com/golang/go/issues/16783

**Comment by gdm85** [comment]
(So in short, the bug was the fact that bytes read was ignored)
